version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ambulanta-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ambulanta_db
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-pw" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ambulanta-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    container_name: ambulanta-app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://db:3307/ambulanta_db
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw
      - RABBITMQ_HOST=rabbitmq

volumes:
  mysql-data: